### PR TITLE
add IntelliJ metadata for android support

### PR DESCRIPTION
**Pull request by devoncarew**
@goderbauer, add IntelliJ metadata to the firebase_messaging project to support working on the Android code

- split the project into 3 modules, the flutter one, the android one, and one for the example sub-project
- add a run configuration for the example main.dart
- include an IntelliJ library reference for the Flutter java jar

This project depends on the user creating an Android sdk named `'Android API 25 Platform'` (instructions here: https://flutter.io/intellij-ide/#edit-android-code).

There's a sketchy bit of this PR - checking in a relative path to the `Flutter for Android` library jar. Not sure how to address that right now.

### CODE REVIEW

**Comment by goderbauer** [comment]
LGTM

Thanks!

**Comment by devoncarew** [comment]
Thanks!

fyi - I don't have the permissions to merge

**Comment by goderbauer** [comment]
I am getting the following message when loading the project in IntelliJ:

screen shot 2017-04-26 at 10 41 12 am

Was that file maybe missing from this PR?

**Comment by devoncarew** [comment]
Yes - sorry; following up.

**Pull request merged**
